holaplex/hub-nfts

- Cargo.lock
- api/Cargo.toml
- api/src/blockchains/solana.rs
- api/src/collection.rs
- api/src/entities/metadata_json_attributes.rs
- api/src/entities/metadata_jsons.rs
- api/src/mutations/drop.rs
- api/src/mutations/mint.rs
- api/src/objects/collection.rs
- api/src/objects/collection_creator.rs
- api/src/objects/drop.rs
- api/src/objects/holder.rs
- api/src/objects/project.rs
- api/src/objects/wallet.rs
Document the graphql objects, queries, and mutations.
> Documenation

- api/src/mutations/drop.rs
- api/src/objects/customer.rs
- api/src/objects/mod.rs
- api/src/queries/customer.rs
- api/src/queries/mod.rs
- Add customer object with a field of mints that pulls the wallet addresses from hub-treasuries and then returns mints from any chain.
> Query customer mints

- README.md
- api/src/blockchains/mod.rs
Add documentation and readme for developers looking to add a new blockchain to Hub
> Basic Documentation

- migration/src/lib.rs
- migration/src/m20230620_160452_make_address_nullable_on_collection_mints.rs
- Address on collection_mints is written at the end of the flow so allow it to be null to start.
> Collection Mints Nullable Migration

- api/src/mutations/drop.rs
- Validate the name and symbol length of a solana NFT
> Validate Solana Name and Symbol Length

- api/src/mutations/drop.rs
- api/src/mutations/transfer.rs
- Validate recipient address
- Check if mint status is **Created**
> Transfer API validations

- api/proto.lock
- api/proto.toml
- api/src/events.rs
- Handlers for mcc submitted and failed events from hub-nfts-solana
> Handle MCC Submitted and Failed Events

- api/src/entities/customer_wallets.rs
- api/src/mutations/mint.rs
- api/src/mutations/transfer.rs
- Make compression flag on mintToCollection optional. Default it to false.
> Default compression flag to false

- Cargo.lock
- api/Cargo.toml
- api/src/lib.rs
- api/src/mutations/collection.rs
- api/src/mutations/mint.rs
- credits.toml
- Have separate credit line items for collections, mints, and minting compressed
> Charge separately for collections, mints, and compressed mints

- api/src/entities/mint_histories.rs
- api/src/entities/nft_transfers.rs
- api/src/mutations/collection.rs
- api/src/mutations/mint.rs
- api/src/mutations/transfer.rs
- api/src/objects/collection.rs
- Add rust docs comments for collection and mint to collection mutations and related objects for auto-generating API documentation
> Collection and Mint to Collection API Documentation

- api/src/dataloaders/mint_histories.rs
- api/src/dataloaders/mod.rs
- api/src/lib.rs
- api/src/objects/customer.rs
- Field for querying the mint_histories of a customer's wallets.
> Query customer mint histories

- api/src/objects/customer.rs
- Need to make sure the addresses of the customer are available for the query.
> Fix MintHistories Field on Customers

- Cargo.lock
- api/Cargo.toml
- api/src/events.rs
- api/src/mutations/collection.rs
- api/src/mutations/drop.rs
- api/src/mutations/mint.rs
- api/src/mutations/transfer.rs
- Update hub-core to 0.4.0
- Check credits and generate deduction id after validations but before record creation
> Prevent Zombie Records From No Credits

- api/src/objects/project.rs
- Check drop and collection are associated to the project before returning
> Ensure drop and collection are associated to project

- api/src/events.rs
Kratos relation needs to be created when update_mint mutation is called and we can use  **SolanaUpdatedCollectionMint**  event.
> Remove SolanaMintUpdated event

- api/src/dataloaders/mint_histories.rs
> Fix Mint History Field on Collection Mint

- api/src/mutations/mint.rs
onconflict statement when saving json already handles it
> Fix: remove metadata json delete from transaction 

- Cargo.lock
- api/Cargo.toml
- api/src/events.rs
- api/src/lib.rs
- api/src/main.rs
- api/src/mutations/mint.rs
> Update hub-core and refactor event loop.

- api/src/mutations/mint.rs
- Lookup the collection separate from finding the random collection_mint
> Query optimizing for mint random

- api/src/dataloaders/collection.rs
- api/src/dataloaders/collection_drop.rs
- api/src/dataloaders/drop.rs
- api/src/dataloaders/drops.rs
- api/src/dataloaders/mod.rs
- api/src/entities/collection_mints.rs
- api/src/entities/collections.rs
- api/src/events.rs
- api/src/handlers.rs
- api/src/lib.rs
- api/src/main.rs
- api/src/mutations/drop.rs
- api/src/mutations/mint.rs
- api/src/objects/collection.rs
- api/src/objects/drop.rs
- api/src/objects/project.rs
- Instead of writing supply and total mints on collection record move to querying and caching count results in redis.
> Redis Cache Total Mints and Supply
